"""Socket.IO data models and protocol enums for real-time messaging."""

from dataclasses import dataclass, field
from enum import IntEnum

from mashumaro import field_options
from mashumaro.config import BaseConfig
from mashumaro.mixins.json import DataClassJSONMixin

from .base import BaseEnum


class SocketIoAction(str, BaseEnum):
    """Action types for Socket.IO message templates."""

    ADDFILE = "DOWNLOADFILE"
    """File download / addition action."""

    ADDFOLDER = "ADDFOLDER"
    """Folder creation action."""

    MODIFYFILE = "MODIFYFILE"
    """File modification action."""

    MODIFYFOLDER = "MODIFYFOLDER"
    """Folder modification / renaming action."""

    DELETEFILE = "DELETEFILE"
    """File deletion action."""

    DELETEFOLDER = "DELETEFOLDER"
    """Folder deletion action."""

    COPYFILE = "COPYFILE"
    """File copy action."""

    COPYFOLDER = "COPYFOLDER"
    """Folder copy action."""

    MOVEFILE = "MOVEFILE"
    """File relocation action."""

    MOVEFOLDER = "MOVEFOLDER"
    """Folder relocation action."""

    WAITING = "WAITING"
    """Pending operation state indicator."""

    STARTSYNC = "STARTSYNC"
    """Synchronization start event signal."""

    QUERY = "QUERY"
    """Query state request signal."""

    SORT = "SORT"
    """Ordering change signal."""

    ADD_DIGEST = "ADD_DIGEST"
    """Digest addition event."""

    UPDATE_DIGEST = "UPDATE_DIGEST"
    """Digest update event."""

    DELETE_DIGEST = "DELETE_DIGEST"
    """Digest deletion event."""


class SocketIoMessageType(str, BaseEnum):
    """Top-level message envelope sync types."""

    FILE_SYN = "FILE-SYN"
    """File synchronization message type."""

    TASK_SYN = "TASK-SYN"
    """Task / to-do synchronization message type."""

    DIGEST_SYN = "DIGEST-SYN"
    """Digest synchronization message type."""


class SocketIoEvent(str, BaseEnum):
    """Socket.IO event names used across client and server."""

    SERVER_MESSAGE = "ServerMessage"
    """Server-to-client message event name."""

    CLIENT_MESSAGE = "ClientMessage"
    """Client-to-server message event name."""

    RATTA_PING = "ratta_ping"
    """Ping/pong heartbeat event name."""

    TODO = "to-do"
    """Task / to-do event channel name."""

    DIGEST = "digest"
    """Digest event channel name."""


class SocketIoClientMessage(str, BaseEnum):
    """Protocol payload string constants for ClientMessage and ping responses."""

    STATUS = "status"
    """Heartbeat check payload string from client."""

    RECEIVED = "Received"
    """Delivery acknowledgment payload string."""


class SocketIoCode(IntEnum):
    """Response status code constants for SocketMessageData envelopes."""

    SUCCESS = 0
    """Success status code for Socket.IO envelopes."""

    FORBIDDEN = 403
    """Forbidden / authentication error status code."""


@dataclass
class SocketHandshakeParams(DataClassJSONMixin):
    """Query parameters required for authenticating a Socket.IO connection."""

    token: str
    """Authentication JWT token issued during user login."""

    type: str = "file"
    """Client connection type (e.g. 'file', 'device', 'web')."""

    random: str = ""
    """Random nonce string generated by the client per connection attempt."""

    sign: str = ""
    """Cryptographic signature calculated over token, type, and random parameters."""

    class Config(BaseConfig):
        serialize_by_alias = True


@dataclass
class SocketIoMessageTemplate(DataClassJSONMixin):
    """Template data for individual file, folder, or task changes in Socket.IO notifications."""

    message_type: SocketIoAction | str | None = field(
        metadata=field_options(alias="messageType"), default=None
    )
    """Action type indicator describing the filesystem or task event (e.g., ADDFOLDER, MOVEFILE)."""

    equipment_no: str | None = field(
        metadata=field_options(alias="equipmentNo"), default=None
    )
    """Hardware serial number or unique device identifier of the origin device."""

    file_type: str | None = field(
        metadata=field_options(alias="fileType"), default=None
    )
    """File format descriptor (e.g., 'note', 'pdf', 'mark', 'folder')."""

    id: int | None = None
    """Database ID of the affected primary file or directory object."""

    new_id: int | None = field(metadata=field_options(alias="newId"), default=None)
    """Target database ID for created or destination objects after copy/move operations."""

    original_name: str | None = field(
        metadata=field_options(alias="originalName"), default=None
    )
    """Source filename or folder name before renaming or relocating."""

    new_name: str | None = field(metadata=field_options(alias="newName"), default=None)
    """Destination filename or folder name after renaming or relocating."""

    md5: str | None = None
    """MD5 content hash of the file payload for integrity verification."""

    size: int | None = None
    """File size in bytes."""

    directory_id: int | None = field(
        metadata=field_options(alias="directoryId"), default=None
    )
    """Database ID of the parent directory containing the item."""

    go_directory_id: int | None = field(
        metadata=field_options(alias="goDirectoryId"), default=None
    )
    """Database ID of the destination folder for move or copy operations."""

    original_path: str | None = field(
        metadata=field_options(alias="originalPath"), default=None
    )
    """Full path to the source file before modification or move."""

    new_path: str | None = field(metadata=field_options(alias="newPath"), default=None)
    """Full path to the target file after modification or move."""

    timestamp: int | None = None
    """Event generation Unix timestamp in milliseconds."""

    class Config(BaseConfig):
        serialize_by_alias = True


@dataclass
class SocketMessageData(DataClassJSONMixin):
    """Top-level envelope for Socket.IO messages exchanged between server and clients."""

    code: str | int | None = None
    """Response status code indicator (e.g., '0' / 0 for success, '403' / 403 for auth error)."""

    msg: str | None = None
    """Human-readable status or error description message."""

    timestamp: int | None = None
    """Envelope dispatch Unix timestamp in milliseconds."""

    msg_type: SocketIoMessageType | str | None = field(
        metadata=field_options(alias="msgType"), default=None
    )
    """Category classification of the envelope payload (e.g., FILE-SYN, TASK-SYN)."""

    data: list[SocketIoMessageTemplate] = field(default_factory=list)
    """List of message change items included in this notification envelope."""

    class Config(BaseConfig):
        serialize_by_alias = True
