import logging
from typing import Optional

from google.genai import types

from supernote.server.config import ServerConfig
from supernote.server.constants import CACHE_BUCKET
from supernote.server.db.session import DatabaseSessionManager
from supernote.server.services.file import FileService
from supernote.server.services.gemini import GeminiService
from supernote.server.services.processor_modules import ProcessorModule
from supernote.server.utils.note_content import get_page_content
from supernote.server.utils.paths import get_page_png_path
from supernote.server.utils.tasks import get_task, update_task_status

logger = logging.getLogger(__name__)


class GeminiOcrModule(ProcessorModule):
    """Module responsible for extracting text from note pages using Gemini OCR.

    This module performs the following:
    1.  Reads the page PNG from Blob Storage (generated by PngConversionModule).
    2.  Sends the image to the Gemini API (via GeminiService).
    3.  Updates the `NotePageContentDO` with the transcribed text.
    4.  Updates the `SystemTaskDO` status to COMPLETED.
    """

    def __init__(
        self,
        file_service: FileService,
        config: ServerConfig,
        gemini_service: GeminiService,
    ) -> None:
        self.file_service = file_service
        self.config = config
        self.gemini_service = gemini_service

    @property
    def name(self) -> str:
        return "GeminiOcrModule"

    @property
    def task_type(self) -> str:
        return "OCR_EXTRACTION"

    async def run_if_needed(
        self,
        file_id: int,
        session_manager: DatabaseSessionManager,
        page_index: Optional[int] = None,
    ) -> bool:
        if page_index is None:
            return False

        task_key = f"page_{page_index}"
        task = await get_task(session_manager, file_id, self.task_type, task_key)

        if task and task.status == "COMPLETED":
            return False

        # Check if PNG exists (Prerequisite)
        png_path = get_page_png_path(file_id, page_index)
        if not await self.file_service.blob_storage.exists(CACHE_BUCKET, png_path):
            return False

        return True

    async def process(
        self,
        file_id: int,
        session_manager: DatabaseSessionManager,
        page_index: Optional[int] = None,
        **kwargs: object,
    ) -> None:
        if page_index is None:
            return

        task_key = f"page_{page_index}"
        logger.info(f"Starting OCR for file {file_id} page {page_index}")

        # 1. Get PNG Content
        png_path = get_page_png_path(file_id, page_index)
        try:
            png_data = b""
            async for chunk in self.file_service.blob_storage.get(
                CACHE_BUCKET, png_path
            ):
                png_data += chunk
        except Exception as e:
            logger.error(f"Failed to read PNG for {file_id} page {page_index}: {e}")
            await update_task_status(
                session_manager, file_id, self.task_type, task_key, "FAILED", str(e)
            )
            return

        # 2. Call Gemini API
        try:
            if not self.gemini_service.is_configured:
                raise ValueError("Gemini API key not configured")

            model_id = self.config.gemini_ocr_model

            prompt = (
                "Transcribe the handwritten text in this image. Output ONLY the text."
            )

            # Use shared service
            response = await self.gemini_service.generate_content(
                model=model_id,
                contents=[
                    types.Content(
                        parts=[
                            types.Part.from_text(text=prompt),
                            types.Part.from_bytes(data=png_data, mime_type="image/png"),
                        ]
                    )
                ],
                config={"media_resolution": "media_resolution_high"},  # type: ignore[arg-type]
            )

            text_content = response.text if response.text else ""

        except Exception as e:
            logger.error(f"Gemini API failed for {file_id} page {page_index}: {e}")
            await update_task_status(
                session_manager, file_id, self.task_type, task_key, "FAILED", str(e)
            )
            return

        # 3. Save Result
        async with session_manager.session() as session:
            content = await get_page_content(session, file_id, page_index)

            if content:
                content.text_content = text_content
            else:
                # Should accept exist if PageHashing ran, but safeguard
                logger.warning(
                    f"NotePageContentDO missing for {file_id} page {page_index} during OCR"
                )
                # Could create, but lacks hash. Skip for now or let Hashing run.

            await session.commit()

        # 4. Update Task Status
        await update_task_status(
            session_manager, file_id, self.task_type, task_key, "COMPLETED"
        )
        logger.info(f"Completed OCR for file {file_id} page {page_index}")
